version: '2'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    ports:
      - 8123:8123

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  mosquitto:
    container_name: mosquitto
    build: mosquitto/build
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/log/:/mqtt/log/
      - ./mosquitto/data/:/mqtt/data/

  bind9:
    container_name: bind9
    build: bind9/build
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
    network_mode: "host"

volumes:
  portainer-data: