
krzysztofowntracks_note4:
  hide_if_away: false
  icon:
  mac:
  name: Krzysztof-owntracks
  picture:
  track: true

androida79e1a42e836f775:
  hide_if_away: false
  icon:
  mac: C0:BD:D1:98:67:3B
  name: Krzysztof-nmap
  picture:
  track: true

androidf01e56250057d92d:
  hide_if_away: false
  icon:
  mac: 84:38:38:D2:B9:0B
  name: Kasia-nmap
  picture:
  track: true


krzysztof_krzysztof_note_4:
  hide_if_away: false
  icon:
  mac:
  name: Krzysztof
  picture:
  track: true
